title       : "TWiLight Menu++ Skins"
description : "A collection of skins for TWiLight Menu++ from DS-Homebrew/twlmenu-extras on GitHub"
repo        : "DS-Homebrew/twlmenu-extras"
color       : "#da4a53"
image       : "https://raw.githubusercontent.com/DS-Homebrew/twlmenu-extras/master/unistore/icons/dsi.png"

sass:
  sass_dir: _sass

collections:
  nintendo-3ds:
    output: true
  nintendo-dsi:
    output: true
  r4-original:
    output: true
  unlaunch:
    output: true
  # wood-ui:
  #   output: true
